### ISSUE TITLE
Not available for selection in setting menu

### ISSUE THREAD

**Issue by mschaaf** [jprichardson/atom-slush-poppies-theme#1]
I use atom 1.0.7 and the theme is not displayed for selection. The theme is showed as installed but I don't get any error messages.

**Comment by jprichardson** [comment]
I have this same issue all of a sudden... not quite sure what's causing it yet...

**Comment by mschaaf** [comment]
found the reason in the package.json there is a key called theme which should be only ui or syntax, but is   currently the name of the theme. Changing this to syntax fixes the issue. I will create a pull request for it.

**Comment by mschaaf** [comment]
Pull request is https://github.com/jprichardson/atom-slush-poppies-theme/pull/2

**Comment by jprichardson** [comment]
Thanks! Published :)
